site_name: Renascitur
theme:
  name: material

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

      # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/)
markdown_extensions:
  - tables
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
- search
- roamlinks 
- callouts
#- ezlinks:
#   wikilinks: true
#   reference_links: true

extra_javascript:
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://unpkg.com/mermaid/dist/mermaid.min.js 
